

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: t38-server-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
spec:
  tls:
  - hosts:
    - api38.my-points.ru
    - web38.my-points.ru
    - insights38.my-points.ru
    secretName: serverpod-tls-t38
  rules:
  - host: "api38.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t38-server-service
            port:
              name: api
  - host: "web38.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t38-server-service
            port:
              name: web
  - host: "insights38.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t38-server-service
            port:
              name: insights
    