
apiVersion: v1
kind: Service
metadata:
  name: t38-server-service
spec:
  selector:
    app: t38-server    
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: insights
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: web
      protocol: TCP
      port: 8082
      targetPort: 8082
    